name = "hellgame"
main = "src/index.js"
compatibility_date = "2024-08-12"

# KV namespace for storing game data
[[kv_namespaces]]
binding = "GAME_DATA"
id = "f8f98b18845a4048b859c7ab04fb4df2"
preview_id = "your-preview-kv-namespace-id"

[vars]
# Add any environment variables here if needed

# Custom domain setup - uncomment and modify these lines:
# [[routes]]
# pattern = "yourdomain.com/*"
# zone_name = "yourdomain.com"
